### ISSUE TITLE
Disjunctions wreck performance

### ISSUE THREAD

**Issue by TuurDutoit** [TuurDutoit/spe-heroku#34]
Using disjunctions for #2 is detrimental for performance: calculation times for my test data set (18 locations) goes from 0.03s to 27s!

Bug OR tools repo: https://github.com/google/or-tools/issues/1345

**Comment by TuurDutoit** [comment]
Joost opened a ticket with Google support. Let's see where that leads

**Comment by amir169** [comment]
> Joost opened a ticket with Google support. Let's see where that leads

Hi!
Any updates on this?

**Comment by TuurDutoit** [comment]
I haven't worked on this project in a long time, so I'm afraid not.
